version: "3"
services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        env_file:
          - .env
        ports: 
          - mode: host 
            protocol: tcp 
            published: ${NGINXPORT:-80}
            target: 80
        volumes:
          - ${WWWROOT}:/www/:${WWWROOTTYPE:-rw}
          - ${LOGROOT:-/.}:/var/log/nginx/:${WWWROOTTYPE:-rw}
          - ./etc/nginx:/etc/nginx/:${WWWROOTTYPE:-rw}
        environment:
          TZ: "Asia/Shanghai"
        restart: always
        networks:
          - default
    
    php-fpm:
        image: holmesian/php7-fpm:latest
        container_name: php-fpm
        hostname: php-fpm
        env_file:
          - .env
        volumes:
          - ${WWWROOT}:/www/:${WWWROOTTYPE:-rw}
          - ${LOGROOT:-/.}:/var/log/php/:${WWWROOTTYPE:-rw}
          - ./etc/php/php.ini:/usr/local/etc/php/php.ini:${WWWROOTTYPE:-rw}
          - ./etc/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:${WWWROOTTYPE:-rw}
        restart: always
        environment:
          TZ: "Asia/Shanghai"
        cap_add:
          - SYS_PTRACE
        networks:
          - default
        
    php5-fpm:
        image: holmesian/php5-fpm:latest
        container_name: php5-fpm
        hostname: php5-fpm
        env_file:
          - .env
        volumes:
          - ${WWWROOT}:/www/:${WWWROOTTYPE}
          - ${LOGROOT:-/.}:/var/log/php/:${WWWROOTTYPE:-rw}
          - ./etc/php/php.ini:/usr/local/etc/php/php.ini:${WWWROOTTYPE:-rw}
          - ./etc/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:${WWWROOTTYPE:-rw}
        restart: always
        environment:
          TZ: "Asia/Shanghai"
        cap_add:
          - SYS_PTRACE
        networks:
          - default


    mysql:
        image: mysql:5
        container_name: mysql
        hostname: mysql
        env_file:
            - .env
        volumes:
            - ${MYSQLDATA}:/var/lib/mysql:${MYSQLDATATYPE:-rw}
            - ./etc/my.cnf:/etc/mysql/mysql.conf.d/my.cnf:${WWWROOTTYPE:-rw}
        restart: always
        ports:
            - "${MYSQLPORT:-3306}:3306"
        networks:
            - default
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQLPASWD:-123456}
            TZ: "Asia/Shanghai"
 
    
            
    redis_db:
        image: redis:6-alpine
        container_name: redis_db
        hostname: redis_db
        restart: always
        environment:
            TZ: "Asia/Shanghai"
        networks:
            - default

networks:
  default:
    driver:
      bridge
