name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u holmesian -p ${{ secrets.DOCKER_HUB_PWD }}
        
      - name: build php5-fpm
        run: |
          docker pull holmesian/php5-fpm:latest
          docker build --cache-from=holmesian/php5-fpm:latest -t holmesian/php5-fpm:latest ./php5-fpm
          docker push holmesian/php5-fpm:latest
          docker build --cache-from=holmesian/php5-fpm:latest -t holmesian/php5-fpm:xdebug ./php5-fpm/ -f ./php5-fpm/Dockerfile-with-xdebug
          docker push holmesian/php5-fpm:xdebug

      - name: build php7-fpm
        run: |
          docker pull holmesian/php7-fpm:latest
          docker build --cache-from=holmesian/php7-fpm:stable -t holmesian/php7-fpm:latest ./php7-fpm
          docker push holmesian/php7-fpm:latest
          docker build --cache-from=holmesian/php7-fpm:stable -t holmesian/php7-fpm:xdebug ./php7-fpm/ -f ./php7-fpm/Dockerfile-with-xdebug
          docker push holmesian/php7-fpm:xdebug

      - name: build php8-arm
        run: |
          docker pull holmesian/php8-fpm-arm:latest
          docker build --cache-from=holmesian/php8-fpm-arm:latest -t holmesian/php8-fpm-arm:latest ./php8-arm
          docker push holmesian/php8-fpm-arm:latest
         
      
